"""
test_pipe.py
~~~~~~~~~~~~
Pytest tests for the AeSys named-pipe CLI server.

Run while AeSys is open with at least one document active:

    python -m pytest Tools/test_pipe.py -v

Requirements: only the Python standard library (no pywin32, no extra packages).
pytest is used only for discovery/reporting; the tests themselves use plain
assert statements.

Pipe path: \\\\.\\pipe\\AeSys   (matches EoPipeProtocol.h kPipeName)
Protocol:  one UTF-8 line in, one UTF-8 line out, both terminated by \\n.
"""

from __future__ import annotations

import json
import pathlib
import sys
import time

import pytest

# Allow running from the repo root without installing the package.
sys.path.insert(0, str(pathlib.Path(__file__).parent))

# ---------------------------------------------------------------------------
# Test-fixture DXF — generated by Tools/test_fixtures/make_test_drawing.py
#
# Geometry (all model space):
#   Layer "Rooms"
#     ROOM_A  closed LWPOLYLINE  (0,0)→(10,0)→(10,8)→(0,8)  area=80, perim=36
#     ROOM_B  closed LWPOLYLINE  (20,0)→(30,0)→(30,6)→(20,6) area=60, perim=32
#     INSERT  DESK at (5,4,0)  inside ROOM_A
#   Layer "Walls"
#     open LWPOLYLINE  (0,0)→(30,0)   — NOT a room
#   Layer "Work"
#     one LINE (50,0)→(60,0)
# ---------------------------------------------------------------------------
_FIXTURE_DXF = str(
    pathlib.Path(__file__).parent / "test_fixtures" / "aesys_test.dxf"
)

from aespy._connection import (
    PIPE_PATH,
    PipeConnection,
    error_code,
    is_error,
    is_ok,
    ok_value,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def pipe() -> PipeConnection:
    """Module-scoped pipe connection — shared across all tests in this file."""
    conn = PipeConnection(timeout=8.0)
    conn.open()
    yield conn
    conn.close()


@pytest.fixture(scope="module")
def fixture_drawing(pipe: PipeConnection) -> None:  # type: ignore[override]
    """Open the deterministic test DXF once for the whole module.

    The file contains known rooms, a seeded block, and a named layer so that
    QUERY ROOM, QUERY BLOCK AT, and QUERY LAYER tests have stable geometry
    to assert against without drawing anything on the fly.
    """
    assert pathlib.Path(_FIXTURE_DXF).exists(), (
        f"Test fixture not found: {_FIXTURE_DXF}\n"
        "Run: python Tools/test_fixtures/make_test_drawing.py"
    )
    r = pipe.send(f"OPENFILE {_FIXTURE_DXF}")
    assert is_ok(r), f"OPENFILE returned: {r!r}"
    # Give AeSys time to load the document and make it the active view.
    time.sleep(1.0)


@pytest.fixture(autouse=True)
def cancel_active_draw(pipe: PipeConnection) -> None:  # type: ignore[override]
    """After every test, cancel any active draw gesture so the next test starts clean."""
    yield
    pipe.send("DRAWESCAPE")


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def cmd(pipe: PipeConnection, command: str) -> str:
    """Send *command* and return the stripped response."""
    return pipe.send(command)


# ---------------------------------------------------------------------------
# Connectivity
# ---------------------------------------------------------------------------

class TestConnectivity:
    def test_pipe_opens(self, pipe: PipeConnection) -> None:
        """The pipe must be reachable — proven by the module-scoped fixture connection."""
        r = pipe.send("REFRESH")
        assert is_ok(r), f"Expected OK, got: {r!r}"

    def test_empty_line_ignored(self, pipe: PipeConnection) -> None:
        """An empty line should return OK without side effects."""
        r = pipe.send("")
        assert is_ok(r), f"Expected OK for empty line, got: {r!r}"


# ---------------------------------------------------------------------------
# Response format
# ---------------------------------------------------------------------------

class TestResponseFormat:
    def test_ok_has_no_extra_whitespace(self, pipe: PipeConnection) -> None:
        r = cmd(pipe, "REFRESH")
        assert r in ("OK", ) or r.startswith("OK "), f"Malformed OK: {r!r}"

    def test_error_format_unknown_command(self, pipe: PipeConnection) -> None:
        r = cmd(pipe, "XYZZY_NOSUCHCMD")
        # Currently ExecuteCommand logs to history but the wire response is OK
        # because dispatch is fire-and-forget.  This test documents the *current*
        # behaviour; update it when structured error propagation lands.
        # For now just check the response is a valid protocol line.
        assert is_ok(r) or is_error(r), f"Not a valid protocol line: {r!r}"

    def test_error_code_helper(self) -> None:
        assert error_code("ERROR:UNKNOWN_COMMAND FOOBAR") == "UNKNOWN_COMMAND"
        assert error_code("ERROR:NO_VIEW") == "NO_VIEW"
        assert error_code("ERROR:INTERNAL pipe write failed") == "INTERNAL"
        assert error_code("OK") == ""
        assert error_code("WARN something") == ""

    def test_ok_value_helper(self) -> None:
        assert ok_value("OK") == ""
        assert ok_value("OK 3.14") == "3.14"
        assert ok_value("OK hello world") == "hello world"
        assert ok_value("ERROR:NO_VIEW") == ""


# ---------------------------------------------------------------------------
# Draw commands (fire-and-forget — verify OK, not geometry)
# ---------------------------------------------------------------------------

class TestDrawCommands:
    """Verify that draw commands are accepted without errors.

    These tests do not assert that specific geometry was created; that would
    require a query interface not yet implemented.  They verify the wire
    protocol response only.
    """

    def test_refresh(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "REFRESH"))

    def test_line_two_points(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "LINE 0,0 100,100"))

    def test_line_relative(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "LINE 50,50 @100,0"))

    def test_circle(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "CIRCLE 200,200 50,200"))

    def test_polyline(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "POLYLINE 0,0 100,0 100,100 0,100"))

    def test_undo(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "UNDO"))

    def test_redo(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "REDO"))


# ---------------------------------------------------------------------------
# Navigation commands
# ---------------------------------------------------------------------------

class TestNavigationCommands:
    def test_zoom_extents(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "ZE"))

    def test_zoom_in(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "ZOOMIN"))

    def test_zoom_out(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "ZOOMOUT"))

    def test_refresh_alias(self, pipe: PipeConnection) -> None:
        assert is_ok(cmd(pipe, "REDRAW"))


# ---------------------------------------------------------------------------
# Sequential commands — verify ordering is preserved
# ---------------------------------------------------------------------------

class TestSequentialOrdering:
    """Send N commands and verify each one gets its own OK, in order."""

    def test_sequence_of_five(self, pipe: PipeConnection) -> None:
        commands = ["REFRESH", "LINE 0,0 10,0", "LINE 10,0 10,10",
                    "UNDO", "UNDO"]
        for c in commands:
            r = pipe.send(c)
            assert is_ok(r), f"Command {c!r} got {r!r}"

    def test_rapid_fire(self, pipe: PipeConnection) -> None:
        """50 REFRESH commands — smoke-test throughput and server stability."""
        for _ in range(50):
            r = pipe.send("REFRESH")
            assert is_ok(r)


# ---------------------------------------------------------------------------
# Reconnect
# ---------------------------------------------------------------------------

class TestReconnect:
    def test_reconnect_after_close(self, pipe: PipeConnection) -> None:
        """Close and re-open the pipe — server must accept a new connection.

        The module-scoped *pipe* fixture holds the only allowed connection
        (server nMaxInstances=1).  Close it first so the server is free to
        accept new clients, then restore it for the fixture's own teardown.
        """
        pipe.close()
        try:
            for _ in range(3):
                with PipeConnection(timeout=5.0) as p:
                    r = p.send("REFRESH")
                assert is_ok(r), f"Got {r!r} on reconnect"
                time.sleep(0.1)
        finally:
            pipe.open()  # restore so fixture teardown doesn't error


# ---------------------------------------------------------------------------
# QUERY TRAP — structured geometry query
# ---------------------------------------------------------------------------

class TestQueryTrap:
    """Verify the QUERY TRAP pipe verb returns valid JSON geometry data."""

    def test_query_trap_empty(self, pipe: PipeConnection) -> None:
        """QUERY TRAP on an empty trap must return OK with groups==0."""
        # Explicitly clear the trap before querying so prior tests don't pollute state.
        pipe.send("CLEARTRAP")
        r = pipe.send("QUERY TRAP")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        assert data["groups"] == 0
        assert data["primitives"] == 0
        assert data["bbox_area"] == 0.0

    def test_query_trap_after_draw_and_trap(self, pipe: PipeConnection) -> None:
        """Draw a line, trap the work layer, query — should report at least 1 group."""
        # Start clean.
        pipe.send("CLEARTRAP")

        # Draw a horizontal line from (0,0) to (100,0).
        assert is_ok(pipe.send("LINE 0,0 100,0"))

        # Trap everything on the current work layer.
        assert is_ok(pipe.send("TRAPWORK"))

        r = pipe.send("QUERY TRAP")
        assert is_ok(r), f"Expected OK from QUERY TRAP, got {r!r}"

        data = json.loads(ok_value(r))
        assert data["groups"] >= 1,     f"Expected at least 1 trapped group, got {data}"
        assert data["primitives"] >= 1, f"Expected at least 1 primitive, got {data}"
        assert data["bbox_width"] > 0.0, f"Expected non-zero bbox_width, got {data}"

        # Clean up.
        pipe.send("CLEARTRAP")
        pipe.send("UNDO")
        pipe.send("REFRESH")

    def test_query_trap_convenience_api(self, pipe: PipeConnection) -> None:
        """query_trap() returns a dict with the expected keys via the convenience wrapper."""
        from aespy import query_trap
        data = query_trap(pipe)
        assert isinstance(data, dict)
        for key in ("groups", "primitives", "bbox", "bbox_width", "bbox_height",
                    "bbox_area", "items"):
            assert key in data, f"Missing key {key!r} in {data}"

    def test_unknown_query_returns_error(self, pipe: PipeConnection) -> None:
        """An unsupported QUERY sub-command must return ERROR:UNKNOWN_QUERY."""
        r = pipe.send("QUERY NOSUCHVERB")
        assert is_error(r), f"Expected ERROR, got {r!r}"
        assert error_code(r) == "UNKNOWN_QUERY", f"Unexpected error code in {r!r}"


# ---------------------------------------------------------------------------
# QUERY BLOCK AT x,y — block-reference geometry query
# ---------------------------------------------------------------------------

class TestQueryBlock:
    """Verify the QUERY BLOCK AT x,y pipe verb returns valid JSON block data.

    Positive tests use the seeded DESK INSERT at (5,4,0) from the fixture DXF.
    """

    # Coordinates of the DESK INSERT in aesys_test.dxf.
    _DESK_X = 5.0
    _DESK_Y = 4.0

    def test_no_block_at_empty_point_returns_error(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Querying a point with no block reference must return ERROR:NO_BLOCK."""
        r = pipe.send("QUERY BLOCK AT -99999,-99999")
        assert is_error(r), f"Expected ERROR at empty point, got {r!r}"
        assert error_code(r) in ("NO_BLOCK", "NO_VIEW", "NO_DOC"), (
            f"Unexpected error code: {r!r}"
        )

    def test_query_block_response_keys(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """DESK INSERT at (5,4) in the fixture returns a dict with all required keys."""
        r = pipe.send(f"QUERY BLOCK AT {self._DESK_X},{self._DESK_Y}")
        assert is_ok(r), (
            f"Expected OK from QUERY BLOCK AT {self._DESK_X},{self._DESK_Y}, got {r!r}\n"
            "Ensure aesys_test.dxf is open (fixture_drawing loaded it)."
        )
        data = json.loads(ok_value(r))

        for key in ("name", "layer", "x", "y", "z",
                    "rotation", "scale_x", "scale_y", "scale_z", "attributes"):
            assert key in data, f"Missing key {key!r} in {data}"

        assert isinstance(data["attributes"], list), "attributes must be a list"
        assert data["name"] == "DESK", f"Expected block name 'DESK', got {data['name']!r}"

    def test_query_block_attribute_values(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The DESK INSERT's LABEL attribute must be present with value 'DESK-1'."""
        r = pipe.send(f"QUERY BLOCK AT {self._DESK_X},{self._DESK_Y}")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        attrs = {a["tag"]: a["value"] for a in data["attributes"]} if data["attributes"] else {}
        # Attribute import is complete; the LABEL tag should be present.
        assert "LABEL" in attrs, f"Expected LABEL attribute, got attrs={attrs}"
        assert attrs["LABEL"] == "DESK-1", f"Expected 'DESK-1', got {attrs['LABEL']!r}"

    def test_query_block_convenience_api(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """query_block() returns a dict with the expected keys for the DESK INSERT."""
        from aespy import query_block
        data = query_block(pipe, self._DESK_X, self._DESK_Y)
        assert isinstance(data, dict)
        assert "name" in data
        assert data["name"] == "DESK"

    def test_unknown_query_error_message_lists_block(
            self, pipe: PipeConnection) -> None:
        """The UNKNOWN_QUERY error detail now mentions BLOCK."""
        r = pipe.send("QUERY XYZZY")
        assert is_error(r)
        assert error_code(r) == "UNKNOWN_QUERY"
        assert "BLOCK" in r, f"Expected BLOCK in error detail: {r!r}"


# ---------------------------------------------------------------------------
# QUERY ROOM x,y — closed-boundary room query
# ---------------------------------------------------------------------------

class TestQueryRoom:
    """Verify the QUERY ROOM x,y pipe verb returns valid JSON room data.

    Positive tests use the two known room polygons from the fixture DXF:
      ROOM_A: 10×8 rectangle, lower-left (0,0),  area=80, perimeter=36
      ROOM_B: 10×6 rectangle, lower-left (20,0), area=60, perimeter=32
    """

    # A point far outside any geometry — must return NOT_FOUND.
    _EMPTY_X = -99999.0
    _EMPTY_Y = -99999.0

    # ROOM_A — centroid well inside the polygon.
    _ROOM_A_X = 5.0
    _ROOM_A_Y = 4.0
    _ROOM_A_AREA = 80.0
    _ROOM_A_PERIMETER = 36.0  # 2*(10+8)

    # ROOM_B — centroid well inside the polygon.
    _ROOM_B_X = 25.0
    _ROOM_B_Y = 3.0
    _ROOM_B_AREA = 60.0
    _ROOM_B_PERIMETER = 32.0  # 2*(10+6)

    def test_no_room_at_empty_point_returns_error(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Querying a point with no enclosing boundary returns ERROR:NOT_FOUND."""
        r = pipe.send(f"QUERY ROOM {self._EMPTY_X},{self._EMPTY_Y}")
        assert is_error(r), f"Expected ERROR at empty point, got {r!r}"
        assert error_code(r) in ("NOT_FOUND", "NO_VIEW", "NO_DOC"), (
            f"Unexpected error code: {r!r}"
        )

    def test_query_room_response_keys(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """ROOM_A centroid returns a dict with all required keys."""
        r = pipe.send(f"QUERY ROOM {self._ROOM_A_X},{self._ROOM_A_Y}")
        assert is_ok(r), (
            f"Expected OK from QUERY ROOM {self._ROOM_A_X},{self._ROOM_A_Y}, got {r!r}\n"
            "Ensure aesys_test.dxf is open and ROOM_A polygon was imported."
        )
        data = json.loads(ok_value(r))

        for key in ("found", "area", "perimeter", "vertex_count", "layer"):
            assert key in data, f"Missing key {key!r} in {data}"

        assert data["found"] is True
        assert isinstance(data["area"], float) and data["area"] > 0.0
        assert isinstance(data["perimeter"], float) and data["perimeter"] > 0.0
        assert isinstance(data["vertex_count"], int) and data["vertex_count"] >= 3
        assert isinstance(data["layer"], str)

    def test_query_room_area_geometry_room_a(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """ROOM_A area and perimeter match the 10×8 rectangle within tolerance."""
        r = pipe.send(f"QUERY ROOM {self._ROOM_A_X},{self._ROOM_A_Y}")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))

        assert abs(data["area"] - self._ROOM_A_AREA) < 1.0, (
            f"area={data['area']:.3f}, expected ~{self._ROOM_A_AREA}"
        )
        assert abs(data["perimeter"] - self._ROOM_A_PERIMETER) < 1.0, (
            f"perimeter={data['perimeter']:.3f}, expected ~{self._ROOM_A_PERIMETER}"
        )
        assert data["vertex_count"] >= 4
        assert data["layer"].upper() == "ROOMS"

    def test_query_room_area_geometry_room_b(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """ROOM_B area and perimeter match the 10×6 rectangle within tolerance."""
        r = pipe.send(f"QUERY ROOM {self._ROOM_B_X},{self._ROOM_B_Y}")
        assert is_ok(r), f"Expected OK for ROOM_B, got {r!r}"
        data = json.loads(ok_value(r))

        assert abs(data["area"] - self._ROOM_B_AREA) < 1.0, (
            f"area={data['area']:.3f}, expected ~{self._ROOM_B_AREA}"
        )
        assert abs(data["perimeter"] - self._ROOM_B_PERIMETER) < 1.0, (
            f"perimeter={data['perimeter']:.3f}, expected ~{self._ROOM_B_PERIMETER}"
        )
        assert data["vertex_count"] >= 4

    def test_query_room_walls_polyline_not_a_room(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The open Walls polyline (0,0)→(30,0) must NOT be found as a room."""
        r = pipe.send("QUERY ROOM 15,-0.5")
        assert is_error(r) and error_code(r) == "NOT_FOUND", (
            f"Open polyline should not match as a room, got {r!r}"
        )

    def test_query_room_outside_boundary_returns_error(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """A point between ROOM_A and ROOM_B must return NOT_FOUND."""
        r = pipe.send("QUERY ROOM 15,5")
        assert is_error(r) and error_code(r) == "NOT_FOUND", (
            f"Point between rooms should return NOT_FOUND, got {r!r}"
        )

    def test_query_room_bad_args_returns_error(
            self, pipe: PipeConnection) -> None:
        """Missing coordinate must return ERROR:BAD_ARGS."""
        r = pipe.send("QUERY ROOM 42")
        assert is_error(r), f"Expected ERROR for missing y coord, got {r!r}"
        assert error_code(r) == "BAD_ARGS", f"Unexpected error code: {r!r}"

    def test_query_room_convenience_api(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """query_room() returns the ROOM_A dict with the expected keys."""
        from aespy import query_room
        data = query_room(pipe, self._ROOM_A_X, self._ROOM_A_Y)
        assert isinstance(data, dict)
        assert "area" in data
        assert data["area"] > 0.0

    def test_unknown_query_error_message_lists_room(
            self, pipe: PipeConnection) -> None:
        """The UNKNOWN_QUERY error detail now mentions ROOM."""
        r = pipe.send("QUERY XYZZY")
        assert is_error(r)
        assert error_code(r) == "UNKNOWN_QUERY"
        assert "ROOM" in r, f"Expected ROOM in error detail: {r!r}"



# ---------------------------------------------------------------------------
# QUERY LAYER name — layer metadata query
# ---------------------------------------------------------------------------

class TestQueryLayer:
    """Verify the QUERY LAYER <name> pipe verb returns valid JSON layer data."""

    # The default layer present in every new AeSys document.
    _DEFAULT_LAYER = "0"

    def test_no_layer_returns_error(self, pipe: PipeConnection) -> None:
        """Querying a non-existent layer name must return ERROR:NOT_FOUND."""
        r = pipe.send("QUERY LAYER __no_such_layer_xyz__")
        assert is_error(r), f"Expected ERROR for unknown layer, got {r!r}"
        assert error_code(r) in ("NOT_FOUND", "NO_DOC"), (
            f"Unexpected error code: {r!r}"
        )

    def test_missing_name_returns_bad_args(self, pipe: PipeConnection) -> None:
        """QUERY LAYER with no name must return ERROR:BAD_ARGS."""
        r = pipe.send("QUERY LAYER")
        assert is_error(r), f"Expected ERROR for missing name, got {r!r}"
        assert error_code(r) == "BAD_ARGS", f"Unexpected error code: {r!r}"

    def test_query_default_layer_response_keys(self, pipe: PipeConnection) -> None:
        """Querying the default layer '0' returns a dict with all required keys."""
        r = pipe.send(f"QUERY LAYER {self._DEFAULT_LAYER}")
        if is_error(r) and error_code(r) == "NOT_FOUND":
            pytest.skip("Default layer '0' not present — document may be empty")

        assert is_ok(r), f"Expected OK from QUERY LAYER, got {r!r}"
        data = json.loads(ok_value(r))

        for key in ("name", "visible", "is_work", "groups", "primitives", "extents"):
            assert key in data, f"Missing key {key!r} in {data}"

        for ekey in ("min_x", "min_y", "max_x", "max_y"):
            assert ekey in data["extents"], (
                f"Missing extents key {ekey!r} in {data['extents']}"
            )

        assert isinstance(data["name"], str)
        assert isinstance(data["visible"], bool)
        assert isinstance(data["is_work"], bool)
        assert isinstance(data["groups"], int) and data["groups"] >= 0
        assert isinstance(data["primitives"], int) and data["primitives"] >= 0

    def test_query_layer_name_matches_request(self, pipe: PipeConnection) -> None:
        """The returned name must match the requested layer name (case-insensitive)."""
        r = pipe.send(f"QUERY LAYER {self._DEFAULT_LAYER}")
        if is_error(r):
            pytest.skip("Default layer not found")
        data = json.loads(ok_value(r))
        assert data["name"].upper() == self._DEFAULT_LAYER.upper(), (
            f"Returned name {data['name']!r} does not match request"
        )

    def test_query_layer_primitive_count_consistent(
            self, pipe: PipeConnection) -> None:
        """Drawing a line on the work layer increases its primitive count."""
        # Get baseline count for the work layer (draw a line to find it).
        pipe.send("LINE 0,0 10,0")
        time.sleep(0.05)

        # Find which layer was written to by querying layer "0".
        r_before = pipe.send(f"QUERY LAYER {self._DEFAULT_LAYER}")
        if is_error(r_before):
            pipe.send("UNDO")
            pytest.skip("Default layer not found")
        before = json.loads(ok_value(r_before))

        # Draw another primitive.
        pipe.send("LINE 0,1 10,1")
        time.sleep(0.05)

        r_after = pipe.send(f"QUERY LAYER {self._DEFAULT_LAYER}")
        after = json.loads(ok_value(r_after))

        assert after["primitives"] >= before["primitives"], (
            f"Primitive count should not decrease after drawing: "
            f"{before['primitives']} -> {after['primitives']}"
        )

        # Clean up.
        pipe.send("UNDO")
        pipe.send("UNDO")
        pipe.send("REFRESH")

    def test_query_layer_convenience_api(self, pipe: PipeConnection) -> None:
        """query_layer() returns a dict or raises RuntimeError — no TypeError."""
        from aespy import query_layer
        try:
            data = query_layer(pipe, self._DEFAULT_LAYER)
            assert isinstance(data, dict)
            assert "primitives" in data
        except RuntimeError:
            pass  # NOT_FOUND is acceptable if layer doesn't exist

    def test_unknown_query_error_message_lists_layer(
            self, pipe: PipeConnection) -> None:
        """The UNKNOWN_QUERY error detail now mentions LAYER."""
        r = pipe.send("QUERY XYZZY")
        assert is_error(r)
        assert error_code(r) == "UNKNOWN_QUERY"
        assert "LAYER" in r, f"Expected LAYER in error detail: {r!r}"


# ---------------------------------------------------------------------------
# QUERY LAYER — fixture-backed layer tests (Rooms / Work layers from the DXF)
# ---------------------------------------------------------------------------

class TestQueryLayerFixture:
    """Layer tests that require the seeded fixture DXF to be open."""

    def test_query_rooms_layer_has_primitives(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The 'Rooms' layer must report at least 3 primitives (2 polygons + 1 insert)."""
        r = pipe.send("QUERY LAYER Rooms")
        assert is_ok(r), f"Expected OK for Rooms layer, got {r!r}"
        data = json.loads(ok_value(r))
        assert data["primitives"] >= 3, (
            f"Expected >=3 primitives on Rooms layer, got {data['primitives']}"
        )
        assert data["name"].upper() == "ROOMS"
        assert data["visible"] is True

    def test_query_work_layer_has_line(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The 'Work' layer must report at least 1 primitive (the seeded line)."""
        r = pipe.send("QUERY LAYER Work")
        assert is_ok(r), f"Expected OK for Work layer, got {r!r}"
        data = json.loads(ok_value(r))
        assert data["primitives"] >= 1, (
            f"Expected >=1 primitive on Work layer, got {data['primitives']}"
        )

    def test_query_rooms_layer_extents(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The Rooms layer extents must encompass the two room polygons (0..30, 0..8)."""
        r = pipe.send("QUERY LAYER Rooms")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        ext = data["extents"]
        assert ext["min_x"] <= 0.5,  f"min_x should be near 0, got {ext['min_x']}"
        assert ext["max_x"] >= 29.5, f"max_x should reach ~30, got {ext['max_x']}"
        assert ext["min_y"] <= 0.5,  f"min_y should be near 0, got {ext['min_y']}"
        assert ext["max_y"] >= 5.5,  f"max_y should reach ~6 or 8, got {ext['max_y']}"


# ---------------------------------------------------------------------------
# QUERY LAYERS — enumerate all model-space layers
# ---------------------------------------------------------------------------

class TestQueryLayers:
    """Tests for QUERY LAYERS (plural batch enumeration)."""

    def test_query_layers_returns_list(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """QUERY LAYERS must return a JSON object with count and layers list."""
        r = pipe.send("QUERY LAYERS")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        assert "count" in data
        assert "layers" in data
        assert isinstance(data["layers"], list)
        assert data["count"] == len(data["layers"])

    def test_query_layers_count_at_least_two(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Fixture has at least Rooms and Work layers."""
        r = pipe.send("QUERY LAYERS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        assert data["count"] >= 2, f"Expected >=2 layers, got {data['count']}"

    def test_query_layers_contains_rooms(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Rooms layer must appear in the list (case-insensitive name match)."""
        r = pipe.send("QUERY LAYERS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        names = [entry["name"].upper() for entry in data["layers"]]
        assert "ROOMS" in names, f"'ROOMS' not found in {names}"

    def test_query_layers_entry_has_required_keys(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Each layer entry must carry name, visible, is_work, groups, primitives."""
        r = pipe.send("QUERY LAYERS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        required = {"name", "visible", "is_work", "groups", "primitives"}
        for entry in data["layers"]:
            missing = required - entry.keys()
            assert not missing, f"Layer entry missing keys {missing}: {entry}"

    def test_query_layers_rooms_has_primitives(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The Rooms layer entry must report at least 3 primitives."""
        r = pipe.send("QUERY LAYERS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        rooms = next(
            (e for e in data["layers"] if e["name"].upper() == "ROOMS"), None
        )
        assert rooms is not None, "Rooms layer missing from QUERY LAYERS result"
        assert rooms["primitives"] >= 3, (
            f"Expected >=3 primitives on Rooms, got {rooms['primitives']}"
        )


# ---------------------------------------------------------------------------
# QUERY ROOMS — enumerate all closed boundaries
# ---------------------------------------------------------------------------

class TestQueryRooms:
    """Tests for QUERY ROOMS (plural batch enumeration)."""

    def test_query_rooms_returns_list(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """QUERY ROOMS must return a JSON object with count and rooms list."""
        r = pipe.send("QUERY ROOMS")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        assert "count" in data
        assert "rooms" in data
        assert isinstance(data["rooms"], list)
        assert data["count"] == len(data["rooms"])

    def test_query_rooms_finds_two_room_polygons(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Fixture has two closed room polygons; must find at least 2."""
        r = pipe.send("QUERY ROOMS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        assert data["count"] >= 2, f"Expected >=2 rooms, got {data['count']}"

    def test_query_rooms_entry_has_required_keys(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Each room entry must carry area, perimeter, centroid_x, centroid_y,
        vertex_count, and layer."""
        r = pipe.send("QUERY ROOMS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        required = {"area", "perimeter", "centroid_x", "centroid_y", "vertex_count", "layer"}
        for entry in data["rooms"]:
            missing = required - entry.keys()
            assert not missing, f"Room entry missing keys {missing}: {entry}"

    def test_query_rooms_areas_positive(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """All room areas must be positive."""
        r = pipe.send("QUERY ROOMS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        for entry in data["rooms"]:
            assert entry["area"] > 0.0, f"Non-positive area: {entry}"

    def test_query_rooms_layer_filter(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """QUERY ROOMS Rooms must return only rooms from the Rooms layer."""
        r = pipe.send("QUERY ROOMS Rooms")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        for entry in data["rooms"]:
            assert entry["layer"].upper() == "ROOMS", (
                f"Expected layer ROOMS, got {entry['layer']!r}"
            )

    def test_query_rooms_known_area(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Fixture room 1 is 10×6=60; room 2 is 8×8=64. Sum must be >= 120."""
        r = pipe.send("QUERY ROOMS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        total_area = sum(e["area"] for e in data["rooms"])
        assert total_area >= 100.0, f"Expected total area >=100, got {total_area:.2f}"


# ---------------------------------------------------------------------------
# QUERY BLOCKS — enumerate all block references
# ---------------------------------------------------------------------------

class TestQueryBlocks:
    """Tests for QUERY BLOCKS (plural batch enumeration)."""

    def test_query_blocks_returns_list(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """QUERY BLOCKS must return a JSON object with count and blocks list."""
        r = pipe.send("QUERY BLOCKS")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        assert "count" in data
        assert "blocks" in data
        assert isinstance(data["blocks"], list)
        assert data["count"] == len(data["blocks"])

    def test_query_blocks_finds_desk_insert(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Fixture has one DESK INSERT; QUERY BLOCKS must find at least one block."""
        r = pipe.send("QUERY BLOCKS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        assert data["count"] >= 1, f"Expected >=1 block reference, got {data['count']}"

    def test_query_blocks_entry_has_required_keys(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """Each block entry must carry name, layer, x, y, z, rotation,
        scale_x, scale_y, scale_z, and attributes."""
        r = pipe.send("QUERY BLOCKS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        required = {"name", "layer", "x", "y", "z",
                    "rotation", "scale_x", "scale_y", "scale_z", "attributes"}
        for entry in data["blocks"]:
            missing = required - entry.keys()
            assert not missing, f"Block entry missing keys {missing}: {entry}"

    def test_query_blocks_contains_desk(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """At least one entry must have name=='DESK' (case-insensitive)."""
        r = pipe.send("QUERY BLOCKS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        names = [e["name"].upper() for e in data["blocks"]]
        assert "DESK" in names, f"DESK not found in block list: {names}"

    def test_query_blocks_desk_attributes(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """The DESK INSERT must carry a LABEL attribute with value 'DESK-1'."""
        r = pipe.send("QUERY BLOCKS")
        assert is_ok(r)
        data = json.loads(ok_value(r))
        desk = next(
            (e for e in data["blocks"] if e["name"].upper() == "DESK"), None
        )
        assert desk is not None
        attribs = {a["tag"].upper(): a["value"] for a in desk["attributes"]}
        assert "LABEL" in attribs, f"LABEL tag missing from DESK attribs: {attribs}"
        assert attribs["LABEL"] == "DESK-1", (
            f"Expected DESK-1, got {attribs['LABEL']!r}"
        )

    def test_query_blocks_layer_filter(
            self, pipe: PipeConnection, fixture_drawing: None) -> None:
        """QUERY BLOCKS Rooms must return only blocks on the Rooms layer."""
        r = pipe.send("QUERY BLOCKS Rooms")
        assert is_ok(r), f"Expected OK, got {r!r}"
        data = json.loads(ok_value(r))
        for entry in data["blocks"]:
            assert entry["layer"].upper() == "ROOMS", (
                f"Expected layer ROOMS, got {entry['layer']!r}"
            )


# ---------------------------------------------------------------------------
# Entry point for direct execution
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))

