#pragma once

// Prototypes for all procedure called directly by Windows

// Dialog procedures

BOOL CALLBACK DlgProcBlockInsert(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcDrawOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcEditTrap_CommandsQuery(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFixupOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcHomePointGo(HWND hDlg, UINT message, WPARAM wParam, LPARAM);
BOOL CALLBACK DlgProcHomePointSet(HWND hDlg, UINT message, WPARAM wParam, LPARAM);
BOOL CALLBACK DlgProcModeLetter(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcModeRevise(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcPipeOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcPipeSymbol(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetPasteLoc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupHatch(HWND, UINT, WPARAM , LPARAM);
BOOL CALLBACK DlgProcSetupNote(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcTrapFilter(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcTrapModify(HWND, UINT, WPARAM, LPARAM);
