// D:\Projects\Eo111222\AeSys\lex.yy.cpp generated by reflex 6.0.0 from D:\Projects\Eo111222\AeSys\lex_rules.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_header_file         "D:\\Projects\\Eo111222\\AeSys\\lex.yy.h"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "D:\\Projects\\Eo111222\\AeSys\\lex.yy.cpp"
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "D:\Projects\Eo111222\AeSys\lex.yy.h"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)(abs)|(acos)|(asin)|(atan)|(string)|(cos)|(exp)|(int)|(ln)|(log)|(sin)|(sqrt)|(tan)|(real)|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))'(?:(?:[0-9])+)-(?:(?:(?:[0-9])+)/(?:(?:[0-9])+))\"?)|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))'(?:(?:[0-9])+)\"?)|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))'(?:(?:[0-9])+\\.(?:[0-9])*)\"?)|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))'(?:\\.(?:[0-9])+)\"?)|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))-(?:(?:(?:[0-9])+)/(?:(?:[0-9])+))(?:'|\"|(?:(?:mm|cm|dm|m|km))))|((?:[\\x2b\\x2d]?)(?:(?:(?:[0-9])+)/(?:(?:[0-9])+))(?:'|\"|(?:(?:mm|cm|dm|m|km))))|((?:(?:[\\x2b\\x2d]?)(?:(?:[0-9])+))(?:'|\"|(?:(?:mm|cm|dm|m|km))))|((?:[\\x2b\\x2d]?)(?:(?:[0-9])+\\.(?:[0-9])*)(?:'|\"|(?:(?:mm|cm|dm|m|km))))|((?:[\\x2b\\x2d]?)(?:\\.(?:[0-9])+)(?:'|\"|(?:(?:mm|cm|dm|m|km))))|((?:[\\x2b\\x2d]?)(?:[0-9])*(?:\\Q.\\E)(?:[0-9])+)|((?:[\\x2b\\x2d]?)(?:[0-9])+(?:\\Q.\\E)(?:[0-9])*)|((?:[0-9])+)|(\"(?:(?:[\\x00-!]|[\\x23-\\x5b]|[\\x5d-\\x7f]|[\\xc2-\\xdf][\\x80-\\xbf]|\\xe0[\\xa0-\\xbf][\\x80-\\xbf]|[\\xe1-\\xec][\\x80-\\xbf][\\x80-\\xbf]|\\xed[\\x80-\\x9f][\\x80-\\xbf]|[\\xee\\xef][\\x80-\\xbf][\\x80-\\xbf]|\\xf0[\\x90-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|[\\xf1-\\xf3][\\x80-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|\\xf4[\\x80-\\x8f][\\x80-\\xbf][\\x80-\\xbf])|\\\\(?:.[\\x80-\\xbf]*))*\")|((?:[A-Z_a-z])(?:(?:[A-Z_a-z])|(?:[0-9]))*)|((?:\\Q**\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|([\\x09\\x0a\\x0d\\x20]+)|((?:.[\\x80-\\xbf]*))";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:15: abs :
#line 15 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 1; }
            break;
          case 2: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:16: acos :
#line 16 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 2; }
            break;
          case 3: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:17: asin :
#line 17 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 3; }
            break;
          case 4: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:18: atan :
#line 18 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 4; }
            break;
          case 5: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:19: string :
#line 19 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 5; }
            break;
          case 6: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:20: cos :
#line 20 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 6; }
            break;
          case 7: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:21: exp :
#line 21 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 7; }
            break;
          case 8: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:22: int :
#line 22 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 8; }
            break;
          case 9: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:23: ln :
#line 23 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 9; }
            break;
          case 10: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:24: log :
#line 24 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 10; }
            break;
          case 11: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:25: sin :
#line 25 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 11; }
            break;
          case 12: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:26: sqrt :
#line 26 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 12; }
            break;
          case 13: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:27: tan :
#line 27 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 13; }
            break;
          case 14: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:28: real :
#line 28 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 14; }

            break;
          case 15: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:31: {signed_integer}\'{integer}-{fraction}\"? :
#line 31 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 19; }
            break;
          case 16: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:32: {signed_integer}\'{integer}\"? :
#line 32 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 19; }

            break;
          case 17: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:35: {signed_integer}\'{int_dot}\"? :
#line 35 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 20; }
            break;
          case 18: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:36: {signed_integer}\'{dot_int}\"? :
#line 36 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 20; }

            break;
          case 19: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:39: {signed_integer}-{fraction}(\'|\"|{metric_units}) :
#line 39 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 21; }
            break;
          case 20: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:40: {sign}{fraction}(\'|\"|{metric_units}) :
#line 40 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 21; }
            break;
          case 21: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:41: {signed_integer}(\'|\"|{metric_units}) :
#line 41 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 21; }
            break;
          case 22: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:42: {sign}{int_dot}(\'|\"|{metric_units}) :
#line 42 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 21; }
            break;
          case 23: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:43: {sign}{dot_int}(\'|\"|{metric_units}) :
#line 43 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 21; }

            break;
          case 24: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:45: {sign}{digit}*"."{digit}+ :
#line 45 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 18; }
            break;
          case 25: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:46: {sign}{digit}+"."{digit}* :
#line 46 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 18; }
            break;
          case 26: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:47: {digit}+ :
#line 47 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 17; }

            break;
          case 27: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:49: \"([^\\\"]|\\.)*\" :
#line 49 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 22; }
            break;
          case 28: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:50: {letter}({letter}|{digit})* :
#line 50 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 23; }

            break;
          case 29: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:52: "**" :
#line 52 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 24; }
            break;
          case 30: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:53: "*" :
#line 53 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 25; }
            break;
          case 31: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:54: "/" :
#line 54 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 26; }
            break;
          case 32: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:55: "+" :
#line 55 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 27; }
            break;
          case 33: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:56: "-" :
#line 56 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 28; }
            break;
          case 34: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:57: "(" :
#line 57 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 29; }
            break;
          case 35: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:58: ")" :
#line 58 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ return 30; }

            break;
          case 36: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:60: [ \t\n\r]+ :
#line 60 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ /* ignore whitespace */ }
            break;
          case 37: // rule D:\Projects\Eo111222\AeSys\lex_rules.l:61: . :
#line 61 "D:\\Projects\\Eo111222\\AeSys\\lex_rules.l"
{ /* error or unexpected char */ }

            break;
        }
  }
}
