//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AeSys.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   101
#define IDR_MAINFRAME_256               102
#define IDR_AESYSTYPE                   103
#define IDR_TRACINGTYPE                 104
#define IDR_LAYER                       106
#define IDR_WINDOW                      107
#define IDR_TRAP                        118
#define ID_INDICATOR_ICON               119
#define ID_INDICATOR_PROGRESS           120
#define IDD_SETUP_COLOR                 121
#define ID_VIEW_PROPERTIESWND           122
#define IDD_UNITS                       123
#define IDD_FILE_BLOCK                  124
#define ID_EXPAND_ALL                   125
#define IDD_SETUP_LINETYPE              126
#define ID_SORTPROPERTIES               135
#define IDD_SET_LENGTH                  136
#define ID_PROPERTIES1                  137
#define IDD_PIPE_SYMBOL                 138
#define IDD_PIPE_OPTIONS                139
#define IDD_SETUP_CONSTRAINTS_GRID      141
#define IDR_PEGSTROKEFONT               142
#define IDD_SELECT_ISOMETRIC_VIEW       143
#define IDD_TRACING_EX                  145
#define IDD_DLGPROC_LPD_OPTIONS         146
#define IDD_SETUP_NOTE                  148
#define IDD_SET_TEXT                    149
#define IDD_ANNOTATE_OPTIONS            150
#define IDD_EDIT_TRAPCOMMANDS_QUERY     151
#define IDD_FIXUP_OPTIONS               152
#define IDD_HOME_POINT_EDIT             153
#define IDD_SET_ANGLE                   154
#define IDD_SETUP_HATCH                 155
#define IDD_TRAP_MODIFY                 156
#define IDD_HOME_POINT_GO               157
#define IDD_TRAP_FILTER                 158
#define IDD_SET_POINT_STYLE             159
#define IDD_INSERT_BLOCK                162
#define IDD_VIEW_PARAMETERS             163
#define IDD_PASTE_POSITION              164
#define IDD_MOUSEKEYS                   165
#define IDD_DRAW_OPTIONS                166
#define IDD_GET_LAYER_NAME              167
#define IDD_SET_SCALE                   168
#define IDD_FILE_MANAGE                 169
#define IDD_ADD_NOTE                    170
#define IDD_EDIT_OPTIONS                171
#define IDD_VIEW_ZOOM                   172
#define ID_SHEETSETUP_FORMFACTOR        176
#define ID_BACKGROUNDIMAGE_LOAD         177
#define ID_BACKGROUNDIMAGE_REMOVE       178
#define ID_VIEW_BACKGROUNDIMAGE         182
#define ID_VIEW_MODEINFORMATION         183
#define IDD_PRINT_EX                    184
#define IDR_TRACING                     187
#define IDR_OUTPUT_POPUP                188
#define IDR_CONTEXT_MENU                189
#define IDR_POPUP_TOOLBAR               191
#define IDR_POPUP_MDITABS               194
#define IDR_PROPERTIES                  195
#define IDB_PROPERTIES_HC               196
#define IDR_MENU_ARGS                   197
#define IDR_MENU_DIRS                   198
#define ID_FILE_SAVE_ALL                199
#define IDI_OUTPUT_WND_HC               243
#define IDI_OUTPUT_WND                  244
#define IDI_PROPERTIES_WND_HC           245
#define IDI_PROPERTIES_WND              246
#define ID_VIEW_OUTPUTWND               247
#define IDR_TRAPR_MODE                  267
#define IDR_TRAP_MODE                   268
#define IDR_EDIT_MODE                   269
#define IDR_DRAW_MODE                   270
#define IDR_ANNOTATE_MODE               271
#define IDR_PIPE_MODE                   272
#define IDR_POWER_MODE                  273
#define IDR_DRAW2_MODE                  274
#define IDR_DIMENSION_MODE              275
#define IDR_CUT_MODE                    276
#define IDR_FIXUP_MODE                  277
#define IDR_NODAL_MODE                  278
#define IDR_NODALR_MODE                 279
#define IDR_LPD_MODE                    280
#define IDD_LAYER_PROPERTIES_MANAGER    286
#define IDB_LAYER_FILTERS               287
#define IDB_LAYER_STATES                288
#define IDB_LAYER_STATES_HC             289
#define IDD_LINEWEIGHT                  301
#define IDD_ACTIVE_VIEW_KEYPLAN         338
#define IDD_LINE_TYPES_DIALOG           342
#define IDC_ARCHITECTURAL               1000
#define IDC_ENGINEERING                 1001
#define IDC_FEET                        1002
#define IDC_INCHES                      1003
#define IDC_METRIC                      1004
#define IDC_TRAP                        1005
#define IDC_TEXT                        1006
#define IDC_RATIO                       1010
#define IDC_X                           1011
#define IDC_Y                           1012
#define IDC_Z                           1013
#define IDC_TEXT_HEIGHT                 1014
#define IDC_PRECISION                   1015
#define IDC_TEXT_ROTATION               1016
#define IDC_PATH_RIGHT                  1017
#define IDC_PATH_LEFT                   1018
#define IDC_PATH_UP                     1019
#define IDC_PATH_DOWN                   1020
#define IDC_TEXT_EXP_FAC                1021
#define IDC_TEXT_SPACING                1022
#define IDC_TEXT_INCLIN                 1023
#define IDC_TEXT_ALIGN_HOR_LEFT         1024
#define IDC_TEXT_ALIGN_HOR_CEN          1025
#define IDC_TEXT_ALIGN_HOR_RIGHT        1026
#define IDC_TEXT_ALIGN_VER_BOT          1027
#define IDC_TEXT_ALIGN_VER_MID          1028
#define IDC_TEXT_ALIGN_VER_TOP          1029
#define IDC_FIL_AREA_HAT_ID             1030
#define IDC_FIL_AREA_HAT_X_SCAL         1031
#define IDC_FIL_AREA_HAT_Y_SCAL         1032
#define IDC_FIL_AREA_HAT_ROT_ANG        1033
#define IDC_WIDTH                       1034
#define IDC_DEPTH                       1035
#define IDC_LEFT                        1036
#define IDC_CENTER                      1037
#define IDC_RIGHT                       1038
#define IDC_MITERED                     1039
#define IDC_RADIAL                      1040
#define IDC_GEN_VANES                   1041
#define IDC_RADIUS_FACTOR               1042
#define IDC_LENS_LENGTH                 1054
#define IDC_FIX_SIZ                     1057
#define IDC_FIX_AX_TOL                  1058
#define IDC_USR_AX_INF_ANG              1063
#define IDC_USR_AX_Z_OFF_ANG            1064
#define IDC_USR_GRID_X_INT              1068
#define IDC_USR_GRID_Y_INT              1069
#define IDC_USR_GRID_Z_INT              1070
#define IDC_GRID_DOT_INT_X              1074
#define IDC_GRID_DOT_INT_Y              1075
#define IDC_GRID_DOT_INT_Z              1076
#define IDC_GRID_LN_INT_X               1077
#define IDC_GRID_LN_INT_Y               1078
#define IDC_GRID_LN_INT_Z               1079
#define IDC_GRID_PTS_DIS_ON             1080
#define IDC_GRID_LNS_DIS_ON             1081
#define IDC_GRID_SNAP_ON                1082
#define IDC_GEOMETRY_LIST               1087
#define IDC_DRWG_REP_DEL                1094
#define IDC_ANN_BUB_RAD                 1099
#define IDC_ANN_BUB_FACETS              1100
#define IDC_ANN_DEF_TXT                 1101
#define IDC_ANN_HOOK_RAD                1102
#define IDC_ANN_GAP_SPACE_FAC           1103
#define IDC_ANN_ARR_SIZ                 1104
#define IDC_ANN_ARR_TYP                 1105
#define IDC_VIEW_NAME_LIST              1121
#define IDC_KEYPLAN_AREA                1124
#define IDC_SAVE                        1127
#define IDC_RECALL                      1128
#define IDC_DIR_LIST                    1149
#define IDC_METRIC_UNITS                1155
#define IDC_EDIT_OP_SIZING              1166
#define IDC_EDIT_OP_ROTATION            1170
#define IDC_EDIT_OP_SIZ_X               1171
#define IDC_EDIT_OP_SIZ_Y               1172
#define IDC_EDIT_OP_SIZ_Z               1173
#define IDC_EDIT_OP_ROT_X               1174
#define IDC_EDIT_OP_ROT_Y               1175
#define IDC_EDIT_OP_ROT_Z               1176
#define IDC_EDIT_OP_MIRRORING           1177
#define IDC_EDIT_OP_MIR_X               1178
#define IDC_EDIT_OP_MIR_Y               1179
#define IDC_EDIT_OP_MIR_Z               1180
#define IDC_TRAP_FILTER_PEN             1185
#define IDC_TRAP_FILTER_LINE            1186
#define IDC_TRAP_FILTER_ELEMENT         1187
#define IDC_TRAP_FILTER_PEN_ID          1188
#define IDC_TRAP_FILTER_ELEMENT_LIST    1190
#define IDC_SCALE                       1191
#define IDC_TRAP_FILTER_LINE_LIST       1192
#define IDC_FRONT_CLIP_DISTANCE         1208
#define IDC_BACK_CLIP_DISTANCE          1209
#define IDC_FILL                        1230
#define IDC_CONSTRAINTS                 1231
#define IDC_TRACLOAK                    1239
#define IDC_TRAFUSE                     1241
#define IDC_LAYMELT                     1243
#define IDC_TRA                         1248
#define IDC_LAYRENAME                   1249
#define IDC_TRAEXCLUDE                  1250
#define IDC_TRAINCLUDE                  1251
#define IDC_GROUPS                      1256
#define IDC_LEFT_DOWN                   1273
#define IDC_EDIT1                       1274
#define IDC_LEFT_UP                     1276
#define IDC_RIGHT_DOWN                  1277
#define IDC_RIGHT_UP                    1278
#define IDC_ARC_3_POINT                 1278
#define IDC_ARC_CENTER_2_POINTS         1279
#define IDC_CURVE_SPLINE                1280
#define IDC_CURVE_FITTED                1281
#define IDC_MARKER_TYPE                 1282
#define IDC_PEN                         1283
#define IDC_LINE                        1284
#define IDC_NAME                        1285
#define IDC_MOD_FILL                    1292
#define IDC_MOD_PEN                     1293
#define IDC_MOD_LINE                    1294
#define IDC_MOD_NOTE                    1295
#define IDC_MOD_MARKER                  1296
#define IDC_UP_ONE_LEVEL                1299
#define IDC_TRAOPEN                     1300
#define IDC_TRAMAP                      1302
#define IDC_TRAVIEW                     1304
#define IDC_FILE_NAME                   1307
#define IDC_NEW_FOLDER                  1308
#define IDC_DESCRIPTION                 1310
#define IDC_LAYER_PREVIEW               1312
#define IDC_SOLO                        1314
#define IDC_BLOCKS_LIST                 1315
#define IDC_REFERENCES                  1316
#define IDC_APPEND                      1320
#define IDC_INSERT                      1320
#define IDC_RADIO1                      1323
#define IDC_RADIO2                      1324
#define IDC_SHEET                       1325
#define IDC_PURGE                       1326
#define IDC_FULL                        1326
#define IDC_GET                         1327
#define IDC_HALF                        1327
#define IDC_QUARTER                     1328
#define IDC_FILES_EX                    1329
#define IDC_BLOCKS                      1330
#define IDC_LOAD                        1331
#define IDC_DISTANCE                    1332
#define IDC_LIST                        1334
#define IDC_TIC_SIZE                    1335
#define IDC_RISEDROP_RADIUS             1336
#define IDC_ANGLE                       1338
#define IDC_APPS                        1339
#define IDC_VIEW_ISO_LEFT               1340
#define IDC_APPS1                       1340
#define IDC_VIEW_ISO_RIGHT              1341
#define IDC_APPS2                       1341
#define IDC_VIEW_ISO_FRONT              1342
#define IDC_VIEW_ISO_BACK               1343
#define IDC_VIEW_ISO_ABOVE              1344
#define IDC_VIEW_ISO_UNDER              1345
#define IDC_GROUP_TREE                  1350
#define IDC_EXTRA_LIST_CTRL             1351
#define IDC_HEIGHT                      1354
#define IDC_FONT_NAME                   1355
#define IDC_POSITION_X                  1356
#define IDC_POSITION_Y                  1357
#define IDC_POSITION_Z                  1358
#define IDC_TARGET_X                    1359
#define IDC_TARGET_Y                    1360
#define IDC_TARGET_Z                    1361
#define IDC_FONT                        1365
#define IDC_CURRENTVIEW                 1366
#define IDC_EXTENTS                     1367
#define IDC_TOFIT                       1368
#define IDC_BEGINWITHTRANSITION         1369
#define IDC_LAYER_FILTER_TREE           1379
#define IDC_LAYERS_LIST_CONTROL         1380
#define IDC_BUTTON_ADD                  1381
#define IDC_BUTTON_CURRENT              1382
#define IDC_STATIC_CURRENT_LAYER        1383
#define IDC_STATIC_LAYER_STATISTIC      1384
#define IDC_STATIC_LINEWEIGHT_ORIGINAL  1385
#define IDC_LIST_LINEWEIGHT             1386
#define IDC_PERSPECTIVE_PROJECTION      1387
#define IDC_APPLY                       1388
#define IDC_LIST1                       1393
#define IDC_STATIC_WORK_LAYER           1406
#define IDC_MFCBUTTON_WORK              1408
#define IDC_MFCBUTTON_NEW               1409
#define IDC_MFCBUTTON_DEL               1410
#define IDC_LINETYPES_LIST_CONTROL      1411
#define IDC_BYBLOCK_BUTTON              1418
#define IDC_BYLAYER_BUTTON              1419
#define IDC_EVEN_COLORS                 1421
#define IDC_GRAYS                       1422
#define IDC_NAMED_COLORS                1423
#define IDC_ODD_COLORS                  1424
#define IDC_COLOR_EDIT                  1425
#define IDC_INDEX_COLOR                 1429
#define IDC_RGBNUMBERS                  1435
#define IDC_SELECTION_COLOR             1436
#define IDC_RADIO_POINT_STYLE_0         1437
#define IDC_RADIO_POINT_STYLE_1         1438
#define IDC_RADIO_POINT_STYLE_2         1439
#define IDC_RADIO_POINT_STYLE_3         1440
#define IDC_RADIO_POINT_STYLE_4         1441
#define IDC_CHECK1                      1442
#define IDC_CHECK2                      1443
#define IDC_CHECK_SQUARE                1443
#define IDC_MFCFONTCOMBO                1448
#define IDC_LINE_TYPES_LIST             1455
#define IDC_CHECK_CIRCLE                1456
#define IDC_EDIT_POINT_SIZE             1457
#define IDS_TOOLBAR_STANDARD            3781
#define IDS_TOOLBAR_CUSTOMIZE           3782
#define IDS_WINDOWS_MANAGER             3783
#define IDS_WORKSPACE                   3786
#define IDS_PROPERTIES                  3787
#define IDS_OUTPUT                      3788
#define IDS_OUTPUT_MESSAGES             3789
#define IDS_OUTPUT_REPORTS              3790
#define IDS_MSG_NO_DET_GROUPS_IN_VIEW   3792
#define IDS_MSG_ZERO_LENGTH_STRING      3793
#define IDS_MSG_PRIM_ADDED_TO_DEL_GROUPS 3794
#define IDS_SEG_DEL_TO_RESTORE          3795
#define IDS_MSG_BAD_PRIM_TYPE           3796
#define IDS_MSG_LAYER_IS_RESIDENT       3797
#define IDS_OPENFILE_FILTER             3798
#define IDS_OPENFILE_FILTER_TRACINGS    3799
#define IDS_OPENFILE_FILTER_PENCOLORS   3800
#define IDS_OPENFILE_FILTER_APPS        3801
#define IDS_OPENFILE_FILTER_BLOCKS      3802
#define IDS_MSG_VERSION_1_JOB_FILE      3803
#define IDS_MSG_TRACING_WRITE_FAILURE   3804
#define IDS_MSG_TRACING_OPEN_FAILURE    3805
#define IDS_MSG_SQRT_NEG                3806
#define IDS_MSG_DDE_INIT_FAILURE        3807
#define IDS_MSG_LAYER_NO_STATIC         3808
#define IDS_MSG_LAYER_NO_HIDDEN         3809
#define IDS_MSG_LAYER_NO_ACTIVE         3810
#define IDS_MSG_CONFIRM_CLOSE           3811
#define IDS_MSG_CONFIRM_EXIT            3812
#define IDS_LAYER_NOT_LOADED            3813
#define IDS_MSG_CONFIRM_BLANK           3814
#define IDS_MSG_LAYER_NO_DELETE_0       3815
#define IDS_MSG_LAYER_NO_DELETE_WORK    3816
#define IDS_MSG_LAYER_NO_RENAME_0       3817
#define IDS_MSG_PTS_COINCIDE            3818
#define IDS_MSG_PTS_COLINEAR            3819
#define IDS_MSG_LPD_NO_END_CAP_LOC      3820
#define IDS_MSG_LPD_NOT_DUCT_SEC        3821
#define IDS_MSG_LPD_UNK_TURN_DIR        3822
#define IDS_MSG_MEM_ALLOC_ERR           3823
#define IDS_MSG_SAVE_STATE_LIST_ERROR   3824
#define IDS_MSG_FILE_LOCKED             3825
#define IDS_MSG_CLIPBOARD_LOCKED        3826
#define IDS_MSG_FILE_NOT_OPEN           3827
#define IDS_MSG_FILE_NOT_FOUND          3828
#define IDS_MSG_SAVE_CHANGES            3829
#define IDS_MSG_DISPOSE_FIRST           3830
#define IDS_MSG_CLOSE_TRACING_FIRST     3831
#define IDS_MSG_SHADOW_FILE_CREATE_FAILURE 3832
#define IDS_MSG_FILE_TYPE_ERROR         3833
#define IDS_MSG_FILE_NOT_A_TRACING      3834
#define IDS_MSG_OPEN_TRACING_NO_CLOAK   3835
#define IDS_MSG_NOTHING_TO_SAVE         3836
#define IDS_MSG_FILE_SHADOWED_AS        3837
#define IDS_MSG_TRACING_SAVE_SUCCESS    3838
#define IDS_MSG_TOO_MANY_PTS            3839
#define IDS_PIPE_SYMBOL_NAMES           3840
#define IDS_HOME_POINT_GO_NAMES         3841
#define IDS_HOME_POINT_SET_NAMES        3842
#define IDS_MSG_LINE_NOT_SELECTED       3843
#define IDS_SAVEFILE_FILTER             3844
#define IDS_METRIC_UNITS                3845
#define IDS_PRIMITIVE_FILTER_LIST       3846
#define IDS_MSG_INVALID_NUMBER_EXTRACT  3847
#define IDS_OPENFILE_LOAD_PENCOLORS_TITLE 3848
#define IDS_MSG_OPENFILE_DIALOG_ERROR   3849
#define IDS_MSG_NO_LINETYPES_DEFINED    3850
#define IDS_MSG_PEGFILE_OPEN_FAILURE    3851
#define ID_OP0                          4112
#define ID_OP1                          4113
#define ID_OP2                          4114
#define ID_OP3                          4115
#define ID_OP4                          4116
#define ID_OP5                          4117
#define ID_OP6                          4118
#define ID_OP7                          4119
#define ID_OP8                          4120
#define ID_OP9                          4121
#define ID_MODE_ANNOTATE                4128
#define ID_MODE_CUT                     4129
#define ID_MODE_DIMENSION               4130
#define ID_MODE_DRAW                    4131
#define ID_MODE_DRAW2                   4132
#define ID_MODE_EDIT                    4133
#define ID_MODE_NODAL                   4134
#define ID_MODE_NODALR                  4135
#define ID_MODE_TRAP                    4136
#define ID_MODE_TRAPR                   4137
#define ID_MODE_FIXUP                   4138
#define ID_MODE_PRIMITIVE_EDIT          4139
#define ID_MODE_PRIMITIVE_MEND          4140
#define ID_MODE_GROUP_EDIT              4141
#define ID_MODE_LPD                     4142
#define ID_MODE_POWER                   4143
#define ID_MODE_PIPE                    4144
#define ID_CURSOR_DEFAULT               4149
#define ID_CURSOR_SYMBOL                4150
#define ID_SETUP_UNITS                  4151
#define ID_VIEW_REFRESH                 4152
#define ID_SETUP_SCALE                  4153
#define ID_FILE_TRACING                 4159
#define ID_SETUP_NOTE                   4160
#define ID_RELATIVEMOVES_RIGHT          4163
#define ID_RELATIVEMOVES_UP             4164
#define ID_RELATIVEMOVES_LEFT           4165
#define ID_RELATIVEMOVES_DOWN           4166
#define ID_RELATIVEMOVES_IN             4167
#define ID_RELATIVEMOVES_OUT            4168
#define ID_RELATIVEMOVES_RIGHTROTATE    4169
#define ID_RELATIVEMOVES_UPROTATE       4170
#define ID_RELATIVEMOVES_LEFTROTATE     4171
#define ID_RELATIVEMOVES_DOWNROTATE     4172
#define ID_TOOLS_GROUP_DELETE           4173
#define ID_TOOLS_PRIMITIVE_SNAPTO       4174
#define ID_TOOLS_PRIMITIVE_SNAPTOENDPOINT 4175
#define ID_TOOLS_GROUP_UNDELETE         4177
#define ID_SETUP_PENCOLOR               4179
#define ID_SETUP_DIMLENGTH              4182
#define ID_SETUP_DIMANGLE               4183
#define ID_SETUP_LINETYPE               4184
#define IDM_RETURN                      4196
#define IDM_ESCAPE                      4197
#define ID_TOOLS_GROUP_BREAK            4254
#define ID_PRIM_BREAK                   4255
#define ID_PENS_REMOVEUNUSEDSTYLES      4260
#define ID_PENS_LOADCOLORS              4261
#define ID_PENS_UNLOADCOLORS            4262
#define ID_PENS_TRANSLATE               4263
#define ID_LAYERS_LOAD                  4265
#define ID_LAYERS_UNLOAD                4266
#define ID_LAYERS_REMOVEEMPTY           4267
#define ID_LAYERS_STATICALL             4268
#define ID_LAYERS_ACTIVEALL             4269
#define ID_BLOCKS_LOAD                  4271
#define ID_BLOCKS_UNLOAD                4272
#define ID_BLOCKS_REMOVEUNUSED          4273
#define ID_PENS_EDITSTYLES              4274
#define ID_TRACINGS_MAPALL              4276
#define ID_TRACINGS_VIEWALL             4277
#define ID_TRACINGS_CLOAKALL            4278
#define ID_PENS_EDITCOLORS              4279
#define ID_PENS_USEDEFAULTS             4280
#define ID_SETUP_SAVEPOINT              4302
#define ID_SETUP_GOTOPOINT              4303
#define ID_FILE_PLOT_QUARTER            4304
#define ID_MAINTENANCE_REMOVEDUPLICATES 4308
#define ID_MAINTENANCE_REMOVEEMPTYNOTES 4311
#define ID_MAINTENANCE_REMOVEEMPTYGROUPS 4312
#define ID_FILE                         4319
#define ID_HELP_CONTENTS                4321
#define ID_CLEAR_VIEWEDTRACINGS         4322
#define ID_CLEAR_WORKINGLAYER           4323
#define ID_CLEAR_MAPPEDTRACINGS         4324
#define ID_RESET_ALL                    4325
#define ID_SETUP_FILL_HOLLOW            4326
#define ID_SETUP_FILL_SOLID             4327
#define ID_SETUP_FILL_PATTERN           4328
#define ID_SETUP_FILL_HATCH             4329
#define ID_PRIM_GOTOCENTERPOINT         4334
#define ID_MODE_REVISE                  4335
#define ID_MODE_LETTER                  4336
#define ID_PRIM_PERPJUMP                4337
#define ID_PRIM_MODIFY_ATTRIBUTES       4338
#define ID_HELP_KEY                     4339
#define ID_FILE_PRINTCURRENTVIEW        4341
#define ID_VIEW_ODOMETER                4342
#define ID_3DVIEWS_TOP                  4344
#define ID_3DVIEWS_BOTTOM               4345
#define ID_3DVIEWS_FRONT                4346
#define ID_3DVIEWS_BACK                 4347
#define ID_3DVIEWS_LEFT                 4348
#define ID_3DVIEWS_RIGHT                4349
#define ID_3DVIEWS_ISOMETRIC            4352
#define ID_VIEW_WIREFRAME               4356
#define ID_TOOLS_GROUP_DELETELAST       4376
#define ID_PRIM_EXTRACTNUM              4377
#define ID_PRIM_EXTRACTSTR              4378
#define ID_EDIT_TRAPCOPY                4380
#define ID_EDIT_TRAPCUT                 4381
#define ID_EDIT_TRAPPASTE               4382
#define ID_FILE_RUN                     4395
#define ID_VIEW_RENDERED                4408
#define ID_VIEW_SOLID                   4409
#define ID_TOOLS_PRIMITVE_DELETE        4417
#define ID_VIEW_PARAMETERS              4436
#define ID_EDIT_IMAGETOCLIPBOARD        4438
#define ID_EDIT_TRACE                   4440
#define ID_SETUP_MOUSEBUTTONS           4450
#define ID_CURSOR_CROSSHAIR             4451
#define ID_SETUP_OPTIONS_DRAW           4508
#define ID_SETUP_OPTIONS_EDIT           4509
#define ID_SETUP_OPTIONS_ANNOTATE       4510
#define ID_SETUP_OPTIONS_2LINE          4511
#define ID_SETUP_OPTIONS_FIXUP          4512
#define ID_SETUP_OPTIONS_DIMENSION      4513
#define ID_WINDOW_PAN_LEFT              4530
#define ID_WINDOW_PAN_UP                4532
#define ID_WINDOW_PAN_DOWN              4533
#define ID_VIEW_ZOOM                    4550
#define ID_WINDOW_ZOOMIN                4551
#define ID_WINDOW_ZOOMOUT               4552
#define ID_WINDOW_NORMAL                4553
#define ID_WINDOW_PAN                   4554
#define ID_TRACING_MAP                  4556
#define ID_TRACING_VIEW                 4557
#define ID_TRACING_CLOAK                4558
#define ID_TRACING_FUSE                 4559
#define ID_LAYER_WORK                   4560
#define ID_LAYER_ACTIVE                 4561
#define ID_LAYER_STATIC                 4562
#define ID_LAYER_HIDDEN                 4563
#define ID_LAYER_MELT                   4564
#define ID_LAYER_LAYERNAME              4565
#define ID_TRACING_TRACINGNAME          4566
#define ID_TRACING_OPEN                 4567
#define ID_EDIT_TRAPQUIT                4569
#define ID_FILE_PLOT_FULL               4570
#define ID_FILE_PLOT_HALF               4571
#define ID_EDIT_TRAPWORK                4572
#define ID_EDIT_TRAPWORKANDACTIVE       4574
#define ID_TRAPCOMMANDS_ADDGROUPS       4575
#define ID_EDIT_TRAPDELETE              4577
#define ID_TRAPCOMMANDS_HIGHLIGHT       4580
#define ID_TRAPCOMMANDS_COMPRESS        4581
#define ID_TRAPCOMMANDS_EXPAND          4582
#define ID_TRAPCOMMANDS_INVERT          4583
#define ID_TRAPCOMMANDS_SQUARE          4584
#define ID_TRAPCOMMANDS_QUERY           4585
#define ID_TRAPCOMMANDS_FILTER          4586
#define ID_FILE_MANAGE                  4587
#define ID_TRAPCOMMANDS_BLOCK           4588
#define ID_TRAPCOMMANDS_UNBLOCK         4590
#define ID_TOOLS_GROUP_EXCHANGE         4591
#define ID_EDIT_SEGTOWORK               4593
#define ID_VIEW_PENWIDTHS               4594
#define ID_SETUP_CONSTRAINTS            4600
#define ID_VIEW_TRUETYPEFONTS           4605
#define ID_VIEW_STATEINFORMATION        4606
#define ID_CLEAR_ACTIVELAYERS           4607
#define ID_CLEAR_ALLLAYERS              4608
#define ID_CLEAR_ALLTRACINGS            4609
#define ID_EDIT_CF_GROUPS               4616
#define ID_EDIT_CF_TEXT                 4618
#define ID_EDIT_CF_IMAGE                4619
#define ID_VIEW_LIGHTING                4621
#define ID_WINDOW_PAN_RIGHT             4623
#define ID_WINDOW_BEST                  4624
#define ID_VIEW_WINDOW                  4625
#define ID_WINDOW_LAST                  4626
#define ID_WINDOW_SHEET                 4627
#define ID_CAMERA_ROTATELEFT            4629
#define ID_CAMERA_ROTATERIGHT           4630
#define ID_CAMERA_ROTATEUP              4631
#define ID_CAMERA_ROTATEDOWN            4632
#define ID_FILE_QUERY                   4633
#define ID_RELATIVEMOVES_ENG_RIGHT      4634
#define ID_RELATIVEMOVES_ENG_DOWN       4635
#define ID_RELATIVEMOVES_ENG_IN         4636
#define ID_RELATIVEMOVES_ENG_OUT        4637
#define ID_RELATIVEMOVES_ENG_LEFT       4638
#define ID_RELATIVEMOVES_ENG_LEFTROTATE 4639
#define ID_RELATIVEMOVES_ENG_RIGHTROTATE 4640
#define ID_RELATIVEMOVES_ENG_DOWNROTATE 4641
#define ID_RELATIVEMOVES_ENG_UP         4642
#define ID_RELATIVEMOVES_ENG_UPROTATE   4643
#define ID_SHIFT_RETURN                 4645
#define ID_VIEW_TOOLBARS                4647
#define ID_VIEW_CUSTOMIZE               4660
#define ID_MDI_TABBED                   4661
#define ID_WINDOW_MANAGER               4662
#define ID_TOOLS_ENTRY                  4668
#define ID_USER_TOOL1                   4671
#define ID_USER_TOOL2                   4672
#define ID_USER_TOOL3                   4673
#define ID_USER_TOOL4                   4674
#define ID_USER_TOOL5                   4675
#define ID_USER_TOOL6                   4676
#define ID_USER_TOOL7                   4677
#define ID_USER_TOOL8                   4678
#define ID_USER_TOOL9                   4679
#define ID_USER_TOOL10                  4680
#define ID_MENU_ITEM1                   4681
#define ID_MENU_ITEM2                   4682
#define ID_MENU_ITEM3                   4683
#define ID_MENU_DIR1                    4684
#define ID_MENU_DIR2                    4685
#define ID_MENU_DIR3                    4686
#define ID_VIEW_FULLSCREEN              4690
#define ID_VIEW_USER_TOOLBAR1           4691
#define ID_VIEW_USER_TOOLBAR2           4692
#define ID_VIEW_USER_TOOLBAR3           4693
#define ID_VIEW_USER_TOOLBAR4           4694
#define ID_VIEW_USER_TOOLBAR5           4695
#define ID_VIEW_USER_TOOLBAR6           4696
#define ID_VIEW_USER_TOOLBAR7           4697
#define ID_VIEW_USER_TOOLBAR8           4698
#define ID_VIEW_USER_TOOLBAR9           4699
#define ID_VIEW_USER_TOOLBAR10          4700
#define ID_SETUP_LAYERPROPERTIES        4733
#define ID_EDIT_FIND_COMBO              4763
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   4806
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  4807
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   4808
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 4809
#define ID_VIEW_APPLOOK_WINDOWS_7       4810
#define ID_VIEW_WINDOW_KEYPLAN          4901
#define ID_WINDOW_ZOOMSPECIAL           4902
#define ID_SETUP_POINTSTYLE             4903
#define ID_DRAW_MODE_OPTIONS            5100
#define ID_DRAW_MODE_POINT              5101
#define ID_DRAW_MODE_LINE               5102
#define ID_DRAW_MODE_POLYGON            5103
#define ID_DRAW_MODE_QUAD               5104
#define ID_DRAW_MODE_ARC                5105
#define ID_DRAW_MODE_ELLIPSE            5106
#define ID_DRAW_MODE_CIRCLE             5107
#define ID_DRAW_MODE_BSPLINE            5108
#define ID_DRAW_MODE_INSERT             5109
#define ID_DRAW_MODE_RETURN             5110
#define ID_DRAW_MODE_ESCAPE             5111
#define ID_DRAW_MODE_SHIFT_RETURN       5112
#define ID_DRAW2_MODE_OPTIONS           5200
#define ID_DRAW2_MODE_JOIN              5201
#define ID_DRAW2_MODE_WALL              5202
#define ID_DRAW2_MODE_3                 5203
#define ID_DRAW2_MODE_4                 5204
#define ID_DRAW2_MODE_5                 5205
#define ID_DRAW2_MODE_6                 5206
#define ID_DRAW2_MODE_7                 5207
#define ID_DRAW2_MODE_8                 5208
#define ID_DRAW2_MODE_9                 5209
#define ID_DRAW2_MODE_RETURN            5210
#define ID_DRAW2_MODE_ESCAPE            5211
#define ID_DRAW2_MODE_SHIFT_RETURN      5212
#define ID_ANNOTATE_MODE_OPTIONS        5300
#define ID_ANNOTATE_MODE_1              5301
#define ID_ANNOTATE_MODE_LINE           5302
#define ID_ANNOTATE_MODE_ARROW          5303
#define ID_ANNOTATE_MODE_BUBBLE         5304
#define ID_ANNOTATE_MODE_HOOK           5305
#define ID_ANNOTATE_MODE_UNDERLINE      5306
#define ID_ANNOTATE_MODE_BOX            5307
#define ID_ANNOTATE_MODE_CUT_IN         5308
#define ID_ANNOTATE_MODE_CONSTRUCTION_LINE 5309
#define ID_ANNOTATE_MODE_RETURN         5310
#define ID_ANNOTATE_MODE_ESCAPE         5311
#define ID_ANNOTATE_MODE_SHIFT_RETURN   5312
#define ID_EDIT_MODE_OPTIONS            5400
#define ID_EDIT_MODE_PIVOT              5401
#define ID_EDIT_MODE_ROTCCW             5402
#define ID_EDIT_MODE_ROTCW              5403
#define ID_EDIT_MODE_MOVE               5404
#define ID_EDIT_MODE_COPY               5405
#define ID_EDIT_MODE_FLIP               5406
#define ID_EDIT_MODE_REDUCE             5407
#define ID_EDIT_MODE_ENLARGE            5408
#define ID_EDIT_MODE_9                  5409
#define ID_EDIT_MODE_RETURN             5410
#define ID_EDIT_MODE_ESCAPE             5411
#define ID_EDIT_MODE_SHIFT_RETURN       5412
#define ID_TRAP_MODE_REMOVE_ADD         5500
#define ID_TRAP_MODE_POINT              5501
#define ID_TRAP_MODE_STITCH             5502
#define ID_TRAP_MODE_3                  5503
#define ID_TRAP_MODE_FIELD              5504
#define ID_TRAP_MODE_LAST               5505
#define ID_TRAP_MODE_ENGAGE             5506
#define ID_TRAP_MODE_7                  5507
#define ID_TRAP_MODE_MENU               5508
#define ID_TRAP_MODE_MODIFY             5509
#define ID_TRAP_MODE_RETURN             5510
#define ID_TRAP_MODE_ESCAPE             5511
#define ID_TRAP_MODE_SHIFT_RETURN       5512
#define ID_TRAPR_MODE_REMOVE_ADD        5600
#define ID_TRAPR_MODE_POINT             5601
#define ID_TRAPR_MODE_STITCH            5602
#define ID_TRAPR_MODE_3                 5603
#define ID_TRAPR_MODE_FIELD             5604
#define ID_TRAPR_MODE_LAST              5605
#define ID_TRAPR_MODE_ENGAGE            5606
#define ID_TRAPR_MODE_7                 5607
#define ID_TRAPR_MODE_MENU              5608
#define ID_TRAPR_MODE_MODIFY            5609
#define ID_TRAPR_MODE_RETURN            5610
#define ID_TRAPR_MODE_ESCAPE            5611
#define ID_TRAPR_MODE_SHIFT_RETURN      5612
#define ID_DIMENSION_MODE_OPTIONS       5700
#define ID_DIMENSION_MODE_ARROW         5701
#define ID_DIMENSION_MODE_LINE          5702
#define ID_DIMENSION_MODE_DLINE         5703
#define ID_DIMENSION_MODE_DLINE2        5704
#define ID_DIMENSION_MODE_EXTEN         5705
#define ID_DIMENSION_MODE_RADIUS        5706
#define ID_DIMENSION_MODE_DIAMETER      5707
#define ID_DIMENSION_MODE_ANGLE         5708
#define ID_DIMENSION_MODE_CONVERT       5709
#define ID_DIMENSION_MODE_RETURN        5710
#define ID_DIMENSION_MODE_ESCAPE        5711
#define ID_DIMENSION_MODE_SHIFT_RETURN  5712
#define ID_CUT_MODE_OPTIONS             5800
#define ID_CUT_MODE_TORCH               5801
#define ID_CUT_MODE_SLICE               5802
#define ID_CUT_MODE_3                   5803
#define ID_CUT_MODE_FIELD               5804
#define ID_CUT_MODE_5                   5805
#define ID_CUT_MODE_6                   5806
#define ID_CUT_MODE_CLIP                5807
#define ID_CUT_MODE_8                   5808
#define ID_CUT_MODE_DIVIDE              5809
#define ID_CUT_MODE_RETURN              5810
#define ID_CUT_MODE_ESCAPE              5811
#define ID_CUT_MODE_SHIFT_RETURN        5812
#define ID_FIXUP_MODE_OPTIONS           5900
#define ID_FIXUP_MODE_REFERENCE         5901
#define ID_FIXUP_MODE_MEND              5902
#define ID_FIXUP_MODE_CHAMFER           5903
#define ID_FIXUP_MODE_FILLET            5904
#define ID_FIXUP_MODE_SQUARE            5905
#define ID_FIXUP_MODE_PARALLEL          5906
#define ID_FIXUP_MODE_7                 5907
#define ID_FIXUP_MODE_8                 5908
#define ID_FIXUP_MODE_9                 5909
#define ID_FIXUP_MODE_RETURN            5910
#define ID_FIXUP_MODE_ESCAPE            5911
#define ID_FIXUP_MODE_SHIFT_RETURN      5912
#define ID_NODAL_MODE_ADDREMOVE         6000
#define ID_NODAL_MODE_POINT             6001
#define ID_NODAL_MODE_LINE              6002
#define ID_NODAL_MODE_AREA              6003
#define ID_NODAL_MODE_MOVE              6004
#define ID_NODAL_MODE_COPY              6005
#define ID_NODAL_MODE_TOLINE            6006
#define ID_NODAL_MODE_TOPOLYGON         6007
#define ID_NODAL_MODE_EMPTY             6008
#define ID_NODAL_MODE_ENGAGE            6009
#define ID_NODAL_MODE_RETURN            6010
#define ID_NODAL_MODE_ESCAPE            6011
#define ID_NODAL_MODE_SHIFT_RETURN      6012
#define ID_PIPE_MODE_OPTIONS            6100
#define ID_PIPE_MODE_1                  6101
#define ID_PIPE_MODE_LINE               6102
#define ID_PIPE_MODE_FITTING            6103
#define ID_PIPE_MODE_DROP               6104
#define ID_PIPE_MODE_RISE               6105
#define ID_PIPE_MODE_6                  6106
#define ID_PIPE_MODE_7                  6107
#define ID_PIPE_MODE_SYMBOL             6108
#define ID_PIPE_MODE_WYE                6109
#define ID_PIPE_MODE_RETURN             6110
#define ID_PIPE_MODE_ESCAPE             6111
#define ID_PIPE_MODE_SHIFT_RETURN       6112
#define ID_POWER_MODE_OPTIONS           6200
#define ID_POWER_MODE_1                 6201
#define ID_POWER_MODE_CIRCUIT           6202
#define ID_POWER_MODE_3                 6203
#define ID_POWER_MODE_GROUND            6204
#define ID_POWER_MODE_HOT               6205
#define ID_POWER_MODE_SWITCH            6206
#define ID_POWER_MODE_NEUTRAL           6207
#define ID_POWER_MODE_HOME              6208
#define ID_POWER_MODE_9                 6209
#define ID_POWER_MODE_RETURN            6210
#define ID_POWER_MODE_ESCAPE            6211
#define ID_POWER_MODE_SHIFT_RETURN      6212
#define ID_LPD_MODE_OPTIONS             6300
#define ID_LPD_MODE_JOIN                6301
#define ID_LPD_MODE_DUCT                6302
#define ID_LPD_MODE_TRANSITION          6303
#define ID_LPD_MODE_TAP                 6304
#define ID_LPD_MODE_ELL                 6305
#define ID_LPD_MODE_TEE                 6306
#define ID_LPD_MODE_UP_DOWN             6307
#define ID_LPD_MODE_8                   6308
#define ID_LPD_MODE_SIZE                6309
#define ID_LPD_MODE_RETURN              6310
#define ID_LPD_MODE_ESCAPE              6311
#define ID_LPD_MODE_SHIFT_RETURN        6312

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        345
#define _APS_NEXT_COMMAND_VALUE         4904
#define _APS_NEXT_CONTROL_VALUE         1458
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
